# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LloydsAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LloydsAssignment
  pod "PromiseKit", "~> 6.8"
  pod "PromiseKit/CoreLocation"

  target 'LloydsAssignmentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LloydsAssignmentUITests' do
    # Pods for testing
    
  end

end
